/*
 * This file is generated by jOOQ.
 */
package com.app.jooq;


import com.app.jooq.tables.ApplicationCursors;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JavaApp extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>java_app</code>
     */
    public static final JavaApp JAVA_APP = new JavaApp();

    /**
     * The table <code>java_app.application_cursors</code>.
     */
    public final ApplicationCursors APPLICATION_CURSORS = ApplicationCursors.APPLICATION_CURSORS;

    /**
     * No further instances allowed
     */
    private JavaApp() {
        super(DSL.name("java_app"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ApplicationCursors.APPLICATION_CURSORS
        );
    }
}
