/*
 * This file is generated by jOOQ.
 */
package com.app.jooq;


import com.app.jooq.tables.ApplicationCursors;
import com.app.jooq.tables.records.ApplicationCursorsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * java_app.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ApplicationCursorsRecord> KEY_APPLICATION_CURSORS_PRIMARY = Internal.createUniqueKey(ApplicationCursors.APPLICATION_CURSORS, DSL.name("KEY_application_cursors_PRIMARY"), new TableField[] { ApplicationCursors.APPLICATION_CURSORS.ID }, true);
}
