/*
 * This file is generated by jOOQ.
 */
package com.app.jooq;


import com.app.jooq.tables.ApplicationCursors;


/**
 * Convenience access to all tables in java_app.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>java_app.application_cursors</code>.
     */
    public static final ApplicationCursors APPLICATION_CURSORS = ApplicationCursors.APPLICATION_CURSORS;
}
