/*
 * This file is generated by jOOQ.
 */
package com.app.jooq.tables.records;


import com.app.jooq.tables.ApplicationCursors;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ApplicationCursorsRecord extends UpdatableRecordImpl<ApplicationCursorsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>java_app.application_cursors.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>java_app.application_cursors.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>java_app.application_cursors.pos_x</code>.
     */
    public void setPosX(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>java_app.application_cursors.pos_x</code>.
     */
    public Integer getPosX() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>java_app.application_cursors.pos_y</code>.
     */
    public void setPosY(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>java_app.application_cursors.pos_y</code>.
     */
    public Integer getPosY() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>java_app.application_cursors.nonce</code>.
     */
    public void setNonce(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>java_app.application_cursors.nonce</code>.
     */
    public String getNonce() {
        return (String) get(3);
    }

    /**
     * Setter for <code>java_app.application_cursors.cursor_id</code>.
     */
    public void setCursorId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>java_app.application_cursors.cursor_id</code>.
     */
    public String getCursorId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>java_app.application_cursors.name</code>.
     */
    public void setName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>java_app.application_cursors.name</code>.
     */
    public String getName() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApplicationCursorsRecord
     */
    public ApplicationCursorsRecord() {
        super(ApplicationCursors.APPLICATION_CURSORS);
    }

    /**
     * Create a detached, initialised ApplicationCursorsRecord
     */
    public ApplicationCursorsRecord(Integer id, Integer posX, Integer posY, String nonce, String cursorId, String name) {
        super(ApplicationCursors.APPLICATION_CURSORS);

        setId(id);
        setPosX(posX);
        setPosY(posY);
        setNonce(nonce);
        setCursorId(cursorId);
        setName(name);
        resetTouchedOnNotNull();
    }
}
