# Database connection settings
hibernate.connection.url=jdbc:mysql://localhost:3306/java_app
hibernate.connection.username=root
hibernate.connection.password=BlueObjectx1

# Echo all executed SQL to console
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true

# Automatically export the schema
hibernate.hbm2ddl.auto=update
